version: '3.3'

networks:
  blockchain_network:
    driver: bridge
    
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - blockchain_network

  blockchain:
    build: ./blockchain
    container_name: blockchain-service
    env_file:
      - .env.blockchain
    depends_on:
      - rabbitmq
    ports:
      - "4000:4000"
    networks:
      - blockchain_network
  
  approval-node1:
    build: ./approval-node
    container_name: approval-node1
    env_file:
      - .env.node1
    depends_on:
      - rabbitmq
      - blockchain
    ports:
      - "4001:4001"
    networks:
      - blockchain_network

  approval-node2:
    build: ./approval-node
    container_name: approval-node2
    env_file:
      - .env.node2
    depends_on:
      - rabbitmq
      - blockchain
    ports:
      - "4002:4001"
    networks:
      - blockchain_network
  
  polling:
    build: ./polling
    container_name: polling
    env_file:
      - .env.polling
    ports:
      - "4003:4003"
    networks:
      - blockchain_network
